DEFAULT_FORMAT_TYPE = "exfat"
DEFAULT_CARD_SIZE = 1060
DEFAULT_MAX_SD_SPEED = 140.0

DEFAULT_MAX_PROCESSES = 4

DEFAULT_ALL = False
DEFAULT_OVERWRITE = False
DEFAULT_VERBOSE = False
DEFAULT_PROMPT_CARD_DETAILS = False

DEFAULT_COPY = True
DEFAULT_FIND = True
DEFAULT_CLEAN = False
DEFAULT_REFRESH = False
DEFAULT_ALLOW_OVERWRITE = False
DEFAULT_CHECK = False
DEFAULT_UPDATE = False
DEFAULT_PRECHECK = False
DEFAULT_DRY_RUN = False
DEFAULT_FORMAT_CARD = False
DEFAULT_IGNORE_ERRORS = False
DEFAULT_QUIET_WORKERS = False
DEFAULT_DEBUG = False

DEFAULT_FILE_EXTENSION = "MP4"

DEFAULT_RCLONE_TRANSFERS = 4
DEFAULT_RCLONE_CHECKERS = 8
DEFAULT_SINGLE_STREAM = False
DEFAULT_VERIFY = False